package com.disector.maploader;

public enum WallKeyword {
    POS,
    PORT,
    MAT, UPPERMAT, LOWERMAT,
    LIGHT,
    OFFSET, SCALE,
    OFFSET_UPPER, SCALE_UPPER,
    OFFSET_LOWER, SCALE_LOWER,
    PEG_LOWER_FRONT, PEG_LOWER_BACK, PEG_UPPER_FRONT, PEG_UPPER_BACK;
}
